version: '3.7'

services:
  producer_service:
    container_name: "producer_service"
    build: ../.
    restart: unless-stopped
    depends_on:
      - rabbit
    environment:
      NODE_PORT: 3000
      AMQP_CONNECTION_STRING: "amqp://admin:admin@rabbitmq:5672/"
      MESSAGE_INTERVAL: 10000
    networks:
      - loadgen

  rabbit:
    container_name: "rabbitmq"
    image: "rabbitmq:3-management"
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "~/docker/rabbitmq/data:/var/lib/rabbitmq"
    networks:
      - loadgen

networks:
  loadgen: