name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull repo
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          docker login docker.pkg.github.com --username ${{ secrets.GITHUB_USERNAME }} --password ${{ secrets.GITHUB_PASSWORD }}
          docker build . --file Dockerfile --tag docker.pkg.github.com/j15r/k8s-scalable-amqp-producer:latest
          docker push docker.pkg.github.com/j15r/k8s-scalable-amqp-producer:latest

        env:
          CI: true
